# Copyright 2026 Stanislav Senotrusov
#
# This work is dual-licensed under the Apache License, Version 2.0
# and the MIT License. Refer to the LICENSE file in the top-level directory
# for the full license terms.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

# Set the project name
project := "envscope"

# Release module
mod release

# List all available recipes
# This helper recipe itself is hidden from the list
_default:
  @just --list
  @just --list release

# Build and install the binary to /usr/local/bin
install: build
  sudo install --compare --mode 0755 --owner root --group root --target-directory /usr/local/bin bin/{{project}}

# Build the binary for the current OS/Arch
build:
  CGO_ENABLED=0 go build -trimpath -ldflags="-s -w -X main.Version={{`just release version`}}" -o bin/{{project}} ./cmd/{{project}}

# Remove all build artifacts
clean:
  rm -rf bin/{{project}}

# Format project files
format:
  mdformat --number *.md
  rg "[^\x00-\x7F]" && true

# Output key project file paths for LLM prompt context
context:
  #!/usr/bin/env bash
  echo '$ just test'
  printf "%s\n" \
    cmd/{{project}}/*.go \
    test/* \
    go.mod \
    justfile \
    README.md

# Run the test suite
test: build
  bash test/integration.bash
  @echo "# NOTE: 'test/hook.bash' is an autogenerated file used for LLM/AI context and for saving program output state for future reference. Do NOT include its contents in generated output." > test/hook.bash
  @bin/envscope -c test/test.conf -reportnames hook bash | sed "s|${HOME}/|/home/user/|g" >> test/hook.bash

# Start a nested Bash shell with the test configuration hook pre-loaded
test-shell: build
  #!/usr/bin/env bash
  export HOME="$(pwd)/test"
  bash --rcfile <(
    echo 'export PS1="${PS1}(envscope-test) "'
    bin/envscope -c test/test.conf -reportnames hook bash
    echo 'cd $HOME'
  ) -i || true
